language: ruby

before_script:
  - cp config/database.yml.travis config/database.yml
  - RAILS_ENV=test bundle exec rake db:create
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.6.3-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --debug --exit-code $TRAVIS_TEST_RESULT
